time_tracking/time_tracking/time_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('dashboard/',views.home,name='dashboard'),
    path('', views.login,name='login'),
    path('register/',views.register,name='register'),
    path('logout/',views.logout,name='logout'),
    path("userdata_create_new/",views.userdata_create_new, name="userdata_create_new"),
    path('load-activity/', views.load_activity, name='ajax_load_activity'),
    path('load-enq-no/', views.load__enq_no, name='ajax_load_enq_no'),
    path('load_name_of_project/', views.load_name_of_project, name='ajax_load_name_of_project'),
    path("user_update_data/<str:pk_id>/",views.user_update_data, name="user_update_data"),
    path("change_password/",views.user_change_password, name="user_change_password"),
    path("user_data_filter/",views.user_data_filter,name="user_data_filter"),
    path('user_time/',views.user_time,name="user_time"),
    path('submitted_data/',views.submitted_data,name='submitted_data'),
    path('Admin_panel/',views.Admin_panel,name='Admin_panel'),


    path('Admin_panel/User/',views.Admin_panel_Reg,name='User_registrion'),
    path('Admin_panel/User/Add/',views.Admin_panel_User_Add,name='Admin_panel_User_Add'),
    path('Admin_panel/User/search/',views.Admin_panel_reg_search,name='Admin_panel_reg_search'),
    path('Admin_panel/user/Update/<str:pk_id>/',views.Admin_panel_user_update_data,name='Admin_panel_user_update_data'),
    path('Admin_panel/user/Delete/<str:pk>/',views.Admin_panel_user_delete_data,name='Admin_panel_user_delete_data'),

    path('Admin_panel/employee_data/',views.Admin_panel_Data,name='Admin_panel_data'),
    path('Admin_panel/employee_data/Update/<str:pk_id>',views.Admin_panel_Data_update,name='Admin_panel_Data_update'),
    path('Admin_panel/employee_data/Delete/<str:pk>/',views.Admin_panel_Data_Delete,name='Admin_panel_Data_Delete'),
 





    path('Admin_panel/employee_data/search/',views.Admin_panel_data_search,name='Admin_panel_data_search'),
    
    path('Admin_panel/employee_data/Activity/Add/',views.Admin_panel_Activity_Add,name='Admin_panel_Activity_Add'),
    path('Admin_panel/employee_data/Activity/',views.Admin_panel_Activity,name='Admin_panel_Activity'),
    path('Admin_panel/employee_data/Activity/Delete/<str:pk>/',views.Admin_panel_Activity_Delete,name='Admin_panel_Activity_Delete'),
    path('Admin_panel/employee_data/Activity/Update/<str:pk_id>/',views.Admin_panel_Activity_Update,name='Admin_panel_Activity_Update'),
    path('Admin_panel/employee_data/Activity/Activity_search/',views.Admin_panel_Activity_search,name='Admin_panel_Activity_search'),


    path('Admin_panel/employee_data/deprtmnt/Search/',views.Admin_panel_deprtmnt_search,name='Admin_panel_deprtmnt_search'),
    path('Admin_panel/employee_data/deprtmnt/',views.Admin_panel_deprtmnt,name='Admin_panel_deprtmnt'),
    path('Admin_panel/employee_data/deprtmnt/Update/<str:pk_id>/',views.Admin_panel_deprtmnt_Update,name='Admin_panel_deprtmnt_Update'),
    path('Admin_panel/employee_data/deprtmnt/Delete/<str:pk>/',views.Admin_panel_deprtmnt_Delete,name='Admin_panel_deprtmnt_Delete'),
    path('Admin_panel/employee_data/deprtmnt/Add/',views.Admin_panel_deprtmnt_Add,name='Admin_panel_deprtmnt_Add'),

    
    path('Admin_panel/employee_data/enquiry_no/',views.Admin_panel_enquiry_no,name='Admin_panel_enquiry_no'),
    path('Admin_panel/employee_data/enquiry_no/Add/',views.Admin_panel_enquiry_no_Add,name='Admin_panel_enquiry_no_Add'),
    path('Admin_panel/employee_data/enquiry_no/Update/<str:pk_id>/',views.Admin_panel_enquiry_no_Update,name='Admin_panel_enquiry_no_Update'),
    path('Admin_panel/employee_data/enquiry_no/Delete/<str:pk>/',views.Admin_panel_enquiry_no_Delete,name='Admin_panel_enquiry_no_Delete'),
    path('Admin_panel/employee_data/enquiry_no/Search/',views.Admin_panel_enquiry_no_Search,name='Admin_panel_enquiry_no_Search'),




    path('Admin_panel/employee_data/loction/Add/',views.Admin_panel_loction_Add,name='Admin_panel_loction_Add'),
    path('Admin_panel/employee_data/location/',views.Admin_panel_loction,name='Admin_panel_loction'),
    path('Admin_panel/employee_data/location/Search/',views.Admin_panel_loction_search,name='Admin_panel_loction_search'),
    path('Admin_panel/employee_data/location/Delete/<str:pk>/',views.Admin_panel_loction_Delete,name='Admin_panel_loction_Delete'),
    path('Admin_panel/employee_data/location/Update/<str:pk_id>/',views.Admin_panel_loction_Update,name='Admin_panel_loction_Update'),


    path('Admin_panel/employee_data/name_of_project/',views.Admin_panel_name_of_project,name='Admin_panel_name_of_project'),
    path('Admin_panel/employee_data/name_of_project/Add/',views.Admin_panel_name_of_project_Add,name='Admin_panel_name_of_project_Add'),
    path('Admin_panel/employee_data/name_of_project/Delete/<str:pk>/',views.Admin_panel_name_of_project_Delete,name='Admin_panel_name_of_project_Delete'),
    path('Admin_panel/employee_data/name_of_project/Update/<str:pk_id>/',views.Admin_panel_name_of_project_Update,name='Admin_panel_name_of_project_Update'),
    path('Admin_panel/employee_data/name_of_project/Search/',views.Admin_panel_name_of_project_Search,name='Admin_panel_name_of_project_Search'),


    path('Admin_panel/employee_data/project_enquiry/',views.Admin_panel_project_enq,name='Admin_panel_project_enq'),
    path('Admin_panel/employee_data/project_enquiry/Search/',views.Admin_panel_project_enq_Search,name='Admin_panel_project_enq_Search'),
    path('Admin_panel/employee_data/project_enquiry/Update/<str:pk_id>/',views.Admin_panel_project_enq_Update,name='Admin_panel_project_enq_Update'),
    path('Admin_panel/employee_data/project_enquiry/Delete/<str:pk>/',views.Admin_panel_project_enq_Delete,name='Admin_panel_project_enq_Delete'),
    path('Admin_panel/employee_data/project_enq/Add/',views.Admin_panel_project_enq_Add,name='Admin_panel_project_enq_Add'),


    path('Admin_panel/employee_data/employee_data/',views.Admin_panel_employee_data,name='Admin_panel_employee_data'),
    # path('Admin_panel/employee_data/employee_data/search/',views.Admin_panel_employee_data_search,name='Admin_panel_employee_data_search'),
    # path('Admin_panel/employee_data/employee_data/Add/',views.Admin_panel_employee_data_Add,name="Admin_panel_employee_data_Add"),
    # path('Admin_panel/employee_data/employee_data/Update/<str:pk_id>/',views.Admin_panel_employee_data_Add,name="Admin_panel_employee_data_Add"),

    path('Admin_panel/employee_data/export_excel/',views.Admin_panel_export_excel_search,name='Admin_panel_export_excel'),
    path('forget_password/',auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.htm',subject_template_name='registration/password_reset_subject.txt',email_template_name='registration/password_reset_email.html'),name='forget_password'),
    path("password_reset/done",auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'),name='password_reset_confirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),name='password_reset_complete'),

]

time_tracking/time_tracking/time_tracking/urls.py
from django.contrib import admin
from django.urls import path,include

admin.site.site_header = "VERTIBLD Administration"
admin.site.site_title = "VERTIBLD Administration"
admin.site.index_title = "VERTIBLD Administration"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('time_app.urls')),
    # path('',include('django.contrib.auth.urls'))
]

time_tracking/time_tracking/time_app/models.py
from django.contrib.auth.models import User
from django.db import models



class Department(models.Model):
    department = models.CharField(max_length=200, verbose_name='Department')
    
    def __str__(self):
        return self.department


class Activity(models.Model):
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    activity = models.CharField(max_length=200,verbose_name='Activity')

    def __str__(self):
        return self.activity
    
class Location(models.Model):
    location = models.CharField(max_length=100,verbose_name='location')

    def __str__(self):
        return self.location
    

class Project_Enq(models.Model):
    projectEnq = models.CharField(max_length=100,verbose_name="Project_Enq")

    def __str__(self):
        return self.projectEnq
    

class Enq_No(models.Model):
    projectEnq = models.ForeignKey(Project_Enq, on_delete=models.CASCADE)
    enq_no = models.CharField(verbose_name='Enq_No',max_length=20)

    def __str__(self):
        return self.enq_no

class Name_of_Project(models.Model):
    projectEnq = models.ForeignKey(Project_Enq, on_delete=models.CASCADE)
    enq_no = models.ForeignKey(Enq_No, on_delete=models.CASCADE)
    name_of_project = models.CharField(verbose_name="Project_Name",max_length=100)


    def __str__(self):
        return self.name_of_project
    


    

class UserData(models.Model):
    username = models.ForeignKey(User, verbose_name='Employeeid', on_delete=models.CASCADE )
    department = models.ForeignKey(Department,on_delete=models.CASCADE,null=False )
    activity = models.ForeignKey(Activity, on_delete=models.CASCADE,null=False )
    location = models.ForeignKey(Location, on_delete=models.CASCADE,null=False )
    projectEnq = models.ForeignKey(Project_Enq, on_delete=models.CASCADE,null=False )
    enq_no = models.ForeignKey(Enq_No, on_delete=models.CASCADE,null=False )
    name_of_project = models.ForeignKey(Name_of_Project, on_delete=models.CASCADE,null=False )
    start_time = models.TimeField(verbose_name="Starting Time",auto_now=False, auto_now_add=False)
    end_time = models.TimeField(verbose_name="Ending Time", auto_now=False,  auto_now_add=False)
    submit_data = models.DateField(verbose_name='Submit Date',auto_now_add=False)
    hours = models.DurationField("Hours",blank=True,null=True)
    

time_tracking/time_tracking/templates/html_files/activity_dropdown.htm
{% for activity in activites %}
<option value="{{ activity.pk }}">{{ activity.activity }}</option>
{% endfor %}

time_tracking/time_tracking/templates/html_files/enq_no_dropdown.htm
<option value="">---------------</option>
{% for enq_no in enq_nos %}
<option value="{{ enq_no.pk }}">{{ enq_no.enq_no }}</option>
{% endfor %}

time_tracking/time_tracking/templates/html_files/name_of_project.htm
{% for name_of_project in nameofprojects %}
<option value="{{ name_of_project.pk }}">{{ name_of_project.name_of_project }}</option>
{% endfor %}

time_tracking/time_tracking/templates/html_files/user_form.htm
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap core CSS -->
    {%load static%}
    <link rel="stylesheet" type="text/css" href="{% static 'css/Home.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/Bootstrap4_css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-timepicker/0.5.2/css/bootstrap-timepicker.min.css" integrity="sha256-Sv44mRstp+agwCWaPO4R+KKV+Az9Cu+qS5/hNRQlHT0=" crossorigin="anonymous" />
    <link rel="stylesheet" href="/static/Bootstrap4_css/bootstrap-timepicker.min.css">
    <link rel="stylesheet" href="/static/fonts/fontawesome-free-5.12.1-web/css/all.min.css">
    <link rel ="stylesheet" href="/static/fonts/fontawesome-free-5.12.1-web/js/all.min.js">
    <title>Time tracker</title>
</head>
<body>
  </style>
  <nav class="navbar navbar-expand-lg navbar-dark ">
    <a class="navbar-brand" href="{% url 'dashboard' %}">
      <img src="/static/image/logo.png"  width="100" height="30" alt="">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'dashboard' %}"><span class="glyphicon glyphicon-chevron-up"></span>Home</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'userdata_create_new' %}">Submit Data</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href= "{% url 'submitted_data' %}">Submitted Data</a>
        </li>
      </ul>
      <span class="navbar-text navbar-dark ">
        <button type="button" class="btn  my-2 my-sm-0" style="background-color: #3e3c3c;"><a href="#" class="ml-2"><strong>Welcome  {{request.user.first_name}}</a></strong></button> 
      </span>
      <span class="navbar-text">
        <a href="{% url 'user_change_password' %}" class="ml-2">Change Password</a>
      </span>
      <span class="navbar-text">
       <a href="{% url 'Admin_panel' %}" class="ml-2">Admin Panel</a></button>
      </span>
      <span class="navbar-text">
        <a href="{% url 'logout' %}" class="ml-2">Logout</a>
      </span>
    </div>
  </nav>
  <div class="container" style="margin-top: 100px;;">
    <div class="row">
        <div class="col-sm-5 col-md-5 col-lg-5 mx-auto " >
            <div class="card bg-light mb-6" style="max-width: 50rem; border-width: 1px 10px; border-style: solid;">
                <div class="card-header" style="text-align: center;">Submit Data</div>
                <div class="card-body">
                  {% if form %}
                  {% block content %}
                  <form method="POST" id="UserDataForm" action="" data-activity-url="{% url 'ajax_load_activity' %}">
                    {% csrf_token %}
                    {{form |crispy}}
                    <button class="btn btn-lg  btn-block text-uppercase" style="background-color: #3e3c3c;" type="submit">save</button>
                    <button class="btn btn-lg  btn-block text-uppercase" style="background-color: #851313;" type="reset">Cancel</button>
                  </form>
                  {% endblock %}
                  {% endif %}
                </div>
                </div>
            </div>
        </div>
    </div>
</div>
  <!-- Bootstrap core JavaScript -->
  <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
  <script src="/static/Jquery/jquery-3.4.1.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <script src="/static/js/bootstrap.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-timepicker/0.5.2/js/bootstrap-timepicker.min.js" integrity="sha256-bmXHkMKAxMZgr2EehOetiN/paT9LXp0KKAKnLpYlHwE=" crossorigin="anonymous"></script>
  <script src="/static/js/bootstrap-timepicker.min.js"></script>
  {% block javascript %}
  <script>
    $("#id_department").change(function () {
      var url = $("#UserDataForm").attr("data-activity-url");  // get the url of the `load_activity` view
      var departmentId = $(this).val();  // get the selected department ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/load-activity/)
        data: {
          'department': departmentId       // add the department id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_activity` view function
          $("#id_activity").html(data);  // replace the contents of the activity input with the data that came from the server
        }
      });

    });

    $("#id_projectEnq").change(function () {  // get the url of the `load_activity` view
      var projectEnqId = $(this).val();  // get the selected department ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url:"{% url 'ajax_load_enq_no'  %}",          // set the url of the request (= localhost:8000/load-activity/)
        data: {
          'projectEnq': projectEnqId       // add the department id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_activity` view function
          $("#id_enq_no").html(data);  // replace the contents of the activity input with the data that came from the server
        }
      });

    });

    $("#id_enq_no").change(function () {  // get the url of the `load_activity` view
      var enq_noId = $(this).val();  // get the selected department ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: "{% url 'ajax_load_name_of_project'  %}",                   // set the url of the request (= localhost:8000/load-activity/)
        data: {
          'enq_no':enq_noId       // add the department id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_activity` view function
          $("#id_name_of_project").html(data);  // replace the contents of the activity input with the data that came from the server
        }
      });
    });
    $('#id_start_time').timepicker({
      timeFormat: 'h:mm:ss p',
      explicitMode: true,
      showMeridian: false,
      icons:{
            up: 'fas fa-angle-up',
            down: 'fas fa-angle-down'
          }
    });
        $('#id_end_time').timepicker({
          timeFormat: 'h:mm:ss p',
          explicitMode:true,
          showMeridian:false,
          icons:{
            up: 'fas fa-angle-up',
            down: 'fas fa-angle-down'
          }
        });
  </script>
{% endblock %}
</body>
</html>

time_tracking/time_tracking/templates/html_files/user_update_data.htm
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Bootstrap core CSS -->
    {%load static%}
    <link rel="stylesheet" type="text/css" href="{% static 'css/Home.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/Bootstrap4_css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-timepicker/0.5.2/css/bootstrap-timepicker.min.css" integrity="sha256-Sv44mRstp+agwCWaPO4R+KKV+Az9Cu+qS5/hNRQlHT0=" crossorigin="anonymous" />
    <link rel="stylesheet" href="/static/Bootstrap4_css/bootstrap-timepicker.min.css">
    <link rel="stylesheet" href="/static/fonts/fontawesome-free-5.12.1-web/css/all.min.css">
    <link rel ="stylesheet" href="/static/fonts/fontawesome-free-5.12.1-web/js/all.min.js">
    <title>Time tracker Update Form</title>
    <link rel="icon" href="/static/image/logo.png" alt="Vertibld" type = "image/x-icon">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark">
    <a class="navbar-brand" href="/dashboard/">
      <img src="/static/image/logo.png"  width="100" height="30" alt="">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'dashboard' %}">Home</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'userdata_create_new' %}">Submit Data</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href= "{% url 'submitted_data' %}">Submitted Data</a>
        </li>
      </ul>
      <span class="navbar-text navbar-dark ">
        <button type="button" class="btn  my-2 my-sm-0" style="background-color: #3e3c3c;"><a href="#" class="ml-2"><strong>Welcome  {{request.user.first_name}}</a></strong></button> 
      </span>
      <span class="navbar-text">
        <button type="button" class="btn  my-2 my-sm-0" style="background-color: #3e3c3c;"><a href="{% url 'user_change_password' %}" class="ml-2">Change Password</a></button>
      </span>
      <span class="navbar-text">
        <button class="btn  my-2 my-sm-0" type="button"><a href="{% url 'Admin_panel' %}" class="ml-2">Admin Panel</a></button>
      </span>
      <span class="navbar-text">
        <a href="{% url 'logout' %}" class="ml-2">Logout</a>
      </span>
    </div>
  </nav>
  <div class="container">
    <div class="row">
      <div class="col-sm">
      </div>
      <div class="col-sm">
        {% if form %}
        {% block content %}
        <!-- <h3>---------More Details-------</h3> -->
        <div class="col-sm-5 col-md-5 col-lg-5 mx-auto " ></div>
        <form method="POST" id="UserDataForm" data-activity-url="{% url 'ajax_load_activity' %}">
          {% csrf_token %}
          {{form |crispy}}
          {% if messages %}
          <div class="messages">
              {% for message in messages %}
              <div{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                  <div class="alert alert-success" role="alert">&nbsp;{{ message }}</div></div>
              {% endfor %}
          </div>
          {% endif %}
          <button class="btn btn-lg  btn-block text-uppercase" style="background-color: #3e3c3c;" type="submit" value="update">save</button>
          <button class="btn btn-lg  btn-block text-uppercase" style="background-color: #851313;" type="reset">Cancel</button>
        </form>
        {% endblock %}
        {% endif %}
        
      </div>
      <div class="col-sm">
      </div>
    </div>
  </div>
  <!-- Bootstrap core JavaScript -->
  <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
  <script src="/static/Jquery/jquery-3.4.1.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <script src="/static/js/bootstrap.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-timepicker/0.5.2/js/bootstrap-timepicker.min.js" integrity="sha256-bmXHkMKAxMZgr2EehOetiN/paT9LXp0KKAKnLpYlHwE=" crossorigin="anonymous"></script>
  <script src="/static/js/bootstrap-timepicker.min.js"></script>
  
  {% block javascript %}
  <script>
     $("#id_department").change(function () {
      var url = $("#UserDataForm").attr("data-activity-url");  // get the url of the `load_activity` view
      var departmentId = $(this).val();  // get the selected department ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/load-activity/)
        data: {
          'department': departmentId       // add the department id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_activity` view function
          $("#id_activity").html(data);  // replace the contents of the activity input with the data that came from the server
        }
      });

    });

    $("#id_projectEnq").change(function () {  // get the url of the `load_activity` view
      var projectEnqId = $(this).val();  // get the selected department ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url:"{% url 'ajax_load_enq_no'  %}",          // set the url of the request (= localhost:8000/load-activity/)
        data: {
          'projectEnq': projectEnqId       // add the department id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_activity` view function
          $("#id_enq_no").html(data);  // replace the contents of the activity input with the data that came from the server
        }
      });

    });

    $("#id_enq_no").change(function () {  // get the url of the `load_activity` view
      var enq_noId = $(this).val();  // get the selected department ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: "{% url 'ajax_load_name_of_project'  %}",                   // set the url of the request (= localhost:8000/load-activity/)
        data: {
          'enq_no':enq_noId       // add the department id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_activity` view function
          $("#id_name_of_project").html(data);  // replace the contents of the activity input with the data that came from the server
        }
      });
    });
    $('#id_start_time').timepicker({
      timeFormat: 'h:mm:ss p',
      explicitMode: true,
      showMeridian: false,
      icons:{
            up: 'fas fa-angle-up',
            down: 'fas fa-angle-down'
          }
    });
    $('#id_end_time').timepicker({
      timeFormat: 'h:mm:ss p',
      explicitMode:true,
      showMeridian:false,
      icons:{
        up: 'fas fa-angle-up',
        down: 'fas fa-angle-down'
        }
        });
        </script>
        {% endblock %}
      </body>
      </html>